services:

  postgres:
    image: postgres
    restart: unless-stopped
    # set shared memory limit when using docker-compose
    # shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: example
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # Can view using `docker exec -it blazor-postgres-1 psql -U myuser -d mydatabase` ?


  # web interface for the database
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080

volumes:
  postgres_data:
    # name: my_postgres_data